// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/toplivo-screens/CatalogFlow.tsx": () => import("../components/mockups/toplivo-screens/CatalogFlow.tsx"),
  "./components/mockups/toplivo-screens/MapScreen.tsx": () => import("../components/mockups/toplivo-screens/MapScreen.tsx"),
  "./components/mockups/toplivo-screens/VaultScreen.tsx": () => import("../components/mockups/toplivo-screens/VaultScreen.tsx")
};
